server:
  port: 35000

spring:
  main:
    web-application-type: reactive
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: msaone
          uri: http://localhost:35001
          predicates:
            - Path=/msaone/**
          filters:
            - RewritePath=/msaone/(?<segment>.*), /$\{segment}
        - id: msatwo
          uri: http://localhost:35002
          predicates:
            - Path=/msatwo/**
          filters:
            - RewritePath=/msatwo/(?<segment>.*), /$\{segment}
        - id: msathree
          uri: http://localhost:35003
          predicates:
            - Path=/msathree/**
          filters:
            - RewritePath=/msathree/(?<segment>.*), /$\{segment}
        - id: msafour
          uri: http://localhost:35004
          predicates:
            - Path=/msafour/**
          filters:
            - RewritePath=/msafour/(?<segment>.*), /$\{segment}
        - id: msafive
          uri: http://localhost:35005
          predicates:
            - Path=/msafive/**
          filters:
            - RewritePath=/msafive/(?<segment>.*), /$\{segment}
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "https://localhost:8765"
            allow-credentials: true
            allowedHeaders:
              - x-requested-with
              - authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
            allowedMethods:
              - POST
              - GET
              - PUT
              - PATCH
              - OPTIONS
              - DELETE
